# Generated by Django 5.2.7 on 2025-11-30 00:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_academic_program_customuser_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_permanent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Estudiante'), ('professor', 'Profesor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[authentication.models.validate_unal_email]),
        ),
    ]
